# Generated by Django 5.2.6 on 2025-09-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='rua',
        ),
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='endereco',
            name='ddd',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='endereco',
            name='gia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='endereco',
            name='ibge',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='endereco',
            name='localidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='endereco',
            name='siafi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
