# Generated by Django 5.2.6 on 2025-09-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_endereco_cidade_remove_endereco_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='ibge',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='siafi',
        ),
    ]
