# Generated by Django 5.2.6 on 2025-09-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('localidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('ibge', models.CharField(blank=True, max_length=10)),
                ('gia', models.CharField(blank=True, max_length=10)),
                ('ddd', models.CharField(blank=True, max_length=3)),
                ('siafi', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
