# Generated by Django 5.2.6 on 2025-09-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viacep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='ibge',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='siafi',
        ),
    ]
